In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [26]:
data = pd.read_csv("1601384482_8387134_image_new_test.txt", sep=',', header=None)
# data = data.iloc[:1000,:]
data

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
0       0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1       0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2       0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3       0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4       0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
9996    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
9997    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
9998    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
9999    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

      777  778  779  780  781  782  783  
0       0    0    0    0    0    0    0  
1       0    0    0    0    0    0    0  
2       0    0    0    0    0    0    0  
3       0    0    0    0    0    0    0  
4       0    0    0    0    0    0    0  
...   ...  ...  ...  ...  ...  ...  ...  
9995    0    0    0    0    0    0    0  
9996    0    0    0    0    0    0    0  
9997    0    0    0    0    0    0    0  
9998    0    0    0    0    0    0    0  
9999    0    0    0    0    0    0    0  

[10000 rows x 784 columns]

In [27]:
data.isnull().sum()

0      0
1      0
2      0
3      0
4      0
      ..
779    0
780    0
781    0
782    0
783    0
Length: 784, dtype: int64

In [28]:
# normalization
def normalize(df):
    return df/255.0

In [29]:
data = normalize(data)

In [30]:
from sklearn.metrics.pairwise import euclidean_distances

In [31]:
def initialize_centroids(data, k):
    # no of attributes
    n = np.shape(data)[1]    
    # initialize centroids as zero matrices    
    centroids = np.mat(np.zeros((k,n)))    
    
#     choose random centroids
    for j in range(k):
        centroids[j,:] = data.iloc[np.random.randint(np.shape(data)[0])]

#     # initialize one random centroid
#     centroids[0,:] = data.iloc[np.random.randint(np.shape(data)[0])]

#     dist_euc = euclidean_distances(centroids[0,:], data)
#     indexes = np.argsort(dist_euc)
#     print(type(indexes))
    
#     centroids[1,:] = data.iloc[indexes[0,-1]]
#     centroids[2,:] = data.iloc[indexes[0,-2]]
        
    return centroids

In [32]:
init_centroids = initialize_centroids(data, k=10)
init_centroids

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [33]:
import scipy.spatial.distance as metric

In [34]:
def euclidean_dist(A, B):
    
    return metric.euclidean(A, B)

In [35]:
euclidean_dist(init_centroids[0], init_centroids[1])

10.824294516862238

In [36]:
def cluster(data, k):

    # Number of rows in dataset
    m = np.shape(data)[0]

    # Hold the instance cluster assignments
    cluster_assignments = np.mat(np.zeros((m, 2)))

    # Initialize centroids
    cents = initialize_centroids(data, k)
    
    # Preserve original centroids
    cents_orig = cents.copy()
    
    changed = True
    num_iter = 0

    # Loop until no changes to cluster assignments
    while changed:

        changed = False

        # For every instance (row in dataset)
        for i in range(m):

            # Track minimum distance, and vector index of associated cluster
            min_dist = np.inf
            min_index = -1

            # Calculate distances
            for j in range(k):

                dist_ji = euclidean_dist(cents[j,:], data.iloc[i,:])
                if dist_ji < min_dist:
                    min_dist = dist_ji
                    min_index = j

            # Check if cluster assignment of instance has changed
            if cluster_assignments[i, 0] != min_index: 
                changed = True

            # Assign instance to appropriate cluster
            cluster_assignments[i, :] = min_index, min_dist**2

        # Update centroid location
        for p in range(k):
            indices = [i for i, x in enumerate(cluster_assignments) if x[0,0] == int(p)]
            cents[p] = np.mean(data.iloc[indices], axis=0)
            
        # Count iterations
        num_iter += 1
        print(cents)
        
    # Return important stuff when done
    return cents, cluster_assignments, num_iter, cents_orig

In [37]:
final_centroids, cluster_ass, iterno, original_centroids = cluster(data, k=10)
array = np.squeeze(np.asarray(cluster_ass[:,0])).astype(np.int64)
array

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ...

array([4, 0, 4, ..., 4, 4, 3])

In [38]:
ans = array.copy()

In [39]:
#             print(indices)
#             centroid_test = np.mean(data[indices], axis = 1)
#             print(centroid_test)

In [40]:
ans

array([4, 0, 4, ..., 4, 4, 3])

In [ ]:
from sklearn.cluster import KMeans
model = KMeans(n_clusters=3, random_state=101, algorithm='full')
ans = model.fit_predict(data)
print(ans)

In [ ]:
model.inertia_

In [ ]:
# to adjust the label size
ans = ans + 1

In [41]:
ans

array([4, 0, 4, ..., 4, 4, 3])

In [42]:
len(ans)

10000

In [43]:
with open('mnist_pred_values.txt', 'w') as filehandle:
    for listitem in ans:
        filehandle.write('%s\n' % listitem)
    print("Wrote",len(ans),"items successfully to mnist_pred_values.txt")

Wrote 10000 items successfully to mnist_pred_values.txt
